# fly.toml app configuration file generated for automated-backup on 2023-07-17T13:17:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "automated-backup"
primary_region = "cdg"

# Launch backup every hour
schedule = "hourly"
