name: Fly Deploy
on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        steps:
            - uses: actions/checkout@v3
            - uses: superfly/flyctl-actions/setup-flyctl@v1
            - run: flyctl deploy --build-only --push --image-label="$GITHUB_SHA"
            - run: flyctl m list -q | xargs -I{} flyctl m destroy "{}"
            - run: flyctl m run registry.fly.io/automated-backup:$GITHUB_SHA --schedule=hourly
